using System;
using System.IO;
using Aspose.Diagram;
using Aspose.Diagram.Saving;

namespace DiagramPageSaveEventDemo
{
    // Callback class that handles page saving events during PDF export
    public class PageSavedCallback : IPageSavingCallback
    {
        private readonly string _outputPath;

        public PageSavedCallback(string outputPath)
        {
            _outputPath = outputPath;
        }

        // Called before a page starts saving (not used here)
        public void PageStartSaving(PageStartSavingArgs args)
        {
            // No action needed at start of page saving
        }

        // Called after a page has been saved
        public void PageEndSaving(PageEndSavingArgs args)
        {
            // Log the page index and total page count
            Console.WriteLine($"Page {args.PageIndex + 1} of {args.PageCount} saved.");

            // Example downstream processing: copy the generated PDF to a backup folder
            try
            {
                string sourcePdf = _outputPath; // Path of the PDF being generated
                string backupFolder = Path.Combine(Path.GetDirectoryName(sourcePdf) ?? "", "BackupPages");
                Directory.CreateDirectory(backupFolder);

                // Create a copy name that includes the page index
                string backupFile = Path.Combine(backupFolder,
                    $"output_page_{args.PageIndex + 1}{Path.GetExtension(sourcePdf)}");

                // Copy the whole PDF (since per-page files aren't generated by Aspose.Diagram)
                File.Copy(sourcePdf, backupFile, true);
                Console.WriteLine($"Backup created: {backupFile}");
            }
            catch (Exception ex)
            {
                // Handle any errors in downstream processing
                Console.WriteLine($"Error during downstream processing for page {args.PageIndex + 1}: {ex.Message}");
            }
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            // Input Visio file (adjust the path as needed)
            string inputPath = "input.vsdx";
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Output PDF file
            string outputPath = "output.pdf";

            // Load the diagram
            using (Diagram diagram = new Diagram(inputPath))
            {
                // Configure PDF save options with a default font and the page-saving callback
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    DefaultFont = "Arial",
                    PageSavingCallback = new PageSavedCallback(outputPath)
                };

                // Save the diagram to PDF; the callback will be invoked per page
                diagram.Save(outputPath, pdfOptions);
            }

            Console.WriteLine("Diagram export completed.");
        }
    }
}