using System;
using System.IO;
using System.Text;
using Aspose.Diagram;
using Aspose.Diagram.Saving;

class Program
{
    static void Main()
    {
        try
        {

            // Load the Visio diagram (replace with your file path)
            var diagram = new Diagram("input.vsdx");

            // Configure SVG save options for the desired page
            var svgOptions = new SVGSaveOptions
            {
                PageIndex = 0,               // 0‑based index of the page to export
                SVGFitToViewPort = true      // Fit the SVG to the viewport
            };

            // Temporary SVG file generated by Aspose.Diagram
            string tempSvgPath = "page0.svg";

            // Save the selected page as SVG using the configured options
            diagram.Save(tempSvgPath, svgOptions);

            // Define custom CSS that will be embedded into the SVG
            string customCss = @"
                .shape { fill: #ffcc00; stroke: #333333; stroke-width: 2; }
                .connector { stroke: #0066ff; stroke-dasharray: 5,5; }
            ";

            // Read the generated SVG content
            string svgContent = File.ReadAllText(tempSvgPath, Encoding.UTF8);

            // Build the <style> element with CDATA to hold the CSS
            string styleTag = $"<style type=\"text/css\"><![CDATA[{customCss}]]></style>";

            // Insert the style element right after the opening <svg> tag
            int insertPos = svgContent.IndexOf('>') + 1;
            svgContent = svgContent.Insert(insertPos, styleTag);

            // Write the final SVG file that includes the custom CSS
            string finalSvgPath = "page0_custom.svg";
            File.WriteAllText(finalSvgPath, svgContent, Encoding.UTF8);

        }
        catch (System.IO.FileNotFoundException ex)
        {
            Console.Error.WriteLine($"[FileNotFoundException] {ex.Message}");
        }
    }
}
