using System;
using System.IO;
using Aspose.Diagram;
using Aspose.Diagram.Saving;

class Program
{
    static void Main()
    {
        try
        {

            // Load the diagram from a file (replace with your actual file path)
            Diagram diagram = new Diagram("input.vsdx");

            // Retrieve a shape (example: first shape on the first page)
            Shape shape = diagram.Pages[0].Shapes[0];

            // Temporary file to store the SVG generated by ToSvg
            string tempSvgPath = Path.GetTempFileName();

            // Save the shape to SVG using the provided ToSvg method
            shape.ToSvg(tempSvgPath, new SVGSaveOptions());

            // Read the SVG content into a string
            string svgContent = File.ReadAllText(tempSvgPath);

            // Destination SVG file path
            string outputSvgPath = "shape.svg";

            // Write the SVG string to the final file using File.WriteAllText
            File.WriteAllText(outputSvgPath, svgContent);

            // Clean up the temporary file
            File.Delete(tempSvgPath);

        }
        catch (System.IO.FileNotFoundException ex)
        {
            Console.Error.WriteLine($"[FileNotFoundException] {ex.Message}");
        }
    }
}
